### ISSUE TITLE
[Feature Request] Add compatibility with SmallTime  

### ISSUE THREAD

**Issue by Chryron** [Aedif/multi-token-edit#3]
I use multiple document selection with mass edit to change scene settings quickly. Currently it isn't possible to change the settings added to scene configuration by SmallTime, with Mass Edit. Adding the ability to do this would be very helpful!

A single scene's settings edited without Multiple Document Selection and Mass Edit:

![image](https://user-images.githubusercontent.com/43299520/186994704-1df17cf2-8c8e-4121-9237-8e34ffae3835.png)

Multiple scenes settings edited without Multiple Document Selection and Mass Edit:

![image](https://user-images.githubusercontent.com/43299520/186994882-f52e1e40-7393-4d57-a6a0-bbc2f9c4fe65.png)

**Comment by Aedif** [comment]
Will push out an update tomorrow to add support.

However due to the way SmallTime orgnaises its fields all of them will be controlled by a single checkbox and will all be included during updates:

![image](https://user-images.githubusercontent.com/7693704/187004905-bc422a7a-1e79-4577-968c-b81c9e4ce892.png)

If you'll want more granular control over which fields will actually be updated I'd recommend you to request SmallTime module's developer to seperate these fields out using "form-groups" like it's done by most other modules out there. It will have minimal impact on the look of that section and will allow MassEdit to better control what is added in the updates:

![image](https://user-images.githubusercontent.com/7693704/187004846-dcf31489-421a-4120-8fec-a8da8303ddb9.png)

**Comment by LukasPrism** [comment]
Hi Aedif… I’m just curious if rather than having a checkbox for each setting you flip the behaviour so that any changes are assumed to be intentional and instead you could have a revert button for each setting instead? That would solve your randomiser UI problem, it could be the dice icon button to begin with, then if the user manually adjusts the setting it switches to the revert button. If the user does revert it switches back to the randomiser button. Just a thought :)

**Comment by Aedif** [comment]
SmallTime fields should now get picked up as of release [1.10.0](https://github.com/Aedif/multi-token-edit/releases/tag/1.10.0)

If your request gets implemented the fields should automatically get split up by the module instead of being treated as a single block.

@LukasPrism I don't think that would work. If I understand your suggestion correctly there wouldn't be a way to select the currently set value in the config window without toggling the field somehow. And anyway the current way the module works is already pretty close to what you described. If the user doesn't want to randomize the field all he needs to do is change the value and the module will automatically select the checkbox for them. No need to fiddle with having to avoid the dice button and select the checkbox themselves. It's only an issue if they want to use the current field as is which would get complicated anyway using your idea.

**Comment by LukasPrism** [comment]
Ah ok yeah that’s fair. The multi-adjust dialogs I’m used to in other software (eg Adobe) work a bit differently. They don’t have a checkbox for each field, but I can see why you’ve done it. eg. I don’t think I’ve seen any “mixed” state checkboxes (the one with a dash or square in it instead of a tick)

**Comment by Aedif** [comment]
If you have any clips or screenshots that showcase it I'll have a look. This is a design I've conjured up out of thin air so it's quite unlikely I've just happened to settle on the best solution.

If you do please raise a new issue since this is not really relevant to the original one and the poster is likely receiving emails that he's not interested in.

**Comment by Aedif** [comment]
Should now be completely resolved with the release 1.14.3 of SmallTime. If there are any additional problems feel free to re-open the issue.
